### ISSUE TITLE
Add all(?) descendants of Victoria

### ISSUE THREAD

**Issue by davorg** [davorg/succession#8]

**Comment by ras52** [comment]
Even if you only want to include people who were ever in first twenty in the line of succession, this is quite difficult because you need to determine who married a Catholic (see #36) or became one.  For example, on the [accession of Edward VII](https://lineofsuccession.co.uk/1901-01-22), there are ten of his descendants in the line of succession.  The next person would be Edward's cousin [Marie, Queen of Romania](https://en.wikipedia.org/wiki/Marie_of_Romania) (1875-1938), but she was disqualified on 10 Jan 1893 as her husband the future [Ferdinand I, King of Romania](https://en.wikipedia.org/wiki/Ferdinand_I_of_Romania) was famously a Catholic.  Their children were raised Eastern Orthodox (ostensibly for which Benedict XV excommunicated Ferdinand), so were in line to the British throne.

Marie's eldest son Carol II (1893-1953) married a Catholic (Elena Lupescu) as his third wife on 3 June 1947; this removed Carol II from his place (17th, I think) in the British line of succession.  Carol II's eldest son [Carol Lambrino](https://en.wikipedia.org/wiki/Carol_Lambrino), by his first wife, was probably never in the line of succession as he was probably considered illegitimate.  Certainly Carol Lambrino was considered illegitimate under Romanian law at the time as the Romanian Supreme Court had annulled Carol II's marriage to his mother well over a year before his birth, though in 1955 the Portuguese courts declared him legitimate, as, many decades later, did the Romanian courts.  Sources like Marlene Eilers' *Queen Victoria's Descendants* do not include either Lambrino or his descendants in the line of succession.

Carol II's only other child was [Michael I, King of Romania](https://en.wikipedia.org/wiki/Michael_I_of_Romania) (1921-2017); he was legitimate and not a Catholic, but he married a Catholic on 10 June 1948.  However their children were raised Romanian Orthodox, so were not disbarred.  This means that at the time of [Elizabeth II's accession](https://lineofsuccession.co.uk/1952-02-06), Michael's daughters Princess Margareta and Princess Elena were next in line to the British crown after Edward VII's descendants.  By the time Michael's next child (Princess Irina) was born, she was out of the top twenty, so there shouldn't be any need to go further with Michael I's descendants unless you plan to support more than just the top twenty in the line of succession at any time.

The next person we need to consider is Carol II's brother, [Prince Nicholas of Romania](https://en.wikipedia.org/wiki/Prince_Nicholas_of_Romania) (1903-1978).  His second wife was Catholic, but his second marriage wasn't until 13 July 1967, at which point he well outside the top twenty.  He had no children.  His youngest brother, Prince Mircea (1913-1916) and eldest sister, Elisabeth, Queen of Greece (1894-1956) both managed to avoid Catholicism, and were childless.

Carol II's second sister was [Maria, Queen of Yugoslavia](https://en.wikipedia.org/wiki/Maria_of_Yugoslavia) (1900-1961).  No Catholic complications there, and none of her children married while they were in the top twenty, so I don't think we need to consider Catholicism for them.  Carol II's youngest sister was [Princess Ileana](https://en.wikipedia.org/wiki/Princess_Ileana_of_Romania) (1909-1991) who married a Catholic in 1931 removing her from the succession, and her children were all brought up Catholic which removes that line.

That's the line of Marie, Queen of Romania exhausted, and by my reckoning from 1925 onwards there's no need to look any further for the top twenty in the British line of succession.

**Comment by davorg** [comment]
I've added what I think are all descendants of Queen Victoria down to her great, great grandchildren. That added 246 people to the database (not including Edward VII's branch that I already had).

I haven't added the exclusions you give above. I'll do that over the next couple of days (thanks, as ever, for the data). Note, I've now extended the lists to display 30 people

**Comment by ras52** [comment]
As you've now gone beyond 20 people, you need to go one generation further in a couple of places.  King Michael I of Romania's eldest four daughters all seem to get into the top 30; it's probably worth adding all five:

* Princess Margareta of Romania (b 1949-03-26)
* Princess Elena of Romania (b 1950-11-15)
* Princess Irina of Romania (b 1953-02-28)
* Princess Sophie of Romania (b 1957-10-29)
* Princess Marie of Romania (b 1964-07-13)

You'll also need the only child of King Peter II of Yugoslavia:
* * Crown Prince Alexander of Yugoslavia (b 1945-07-27)

Not sure any others are necessary, though you might choose to take the descendants of Queen Marie of Romania (formerly Princess Marie of Edinburgh) one generation further.

**Comment by ras52** [comment]
By my reckoning, you probably now have the data to get the top 30 list all the way back to about 1880.
